apiVersion: apps/v1
kind: Deployment
metadata:
  name: meine-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meine-app
  template:
    metadata:
      labels:
        app: meine-app
    spec:
      containers:
        - name: meine-app
          image: meine-app:latest
          imagePullPolicy: Never   # Kubernetes versucht NICHT, das Image aus dem Internet zu holen
          ports:
            - containerPort: 80
