---
- name: Install Docker, Kubernetes, clone GitHub repo and build container
  hosts: all
  become: yes

  vars:
    github_repo: "https://github.com/dein-benutzername/dein-repo.git"
    app_directory: "/opt/app"
    docker_image_name: "meine-app:latest"

  tasks:

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present
        filename: docker

    - name: Install Docker
      apt:
        name: [docker-ce, docker-ce-cli, containerd.io]
        state: present
        update_cache: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add Kubernetes apt key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes apt repository
      apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
        filename: kubernetes

    - name: Install Kubernetes tools
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold Kubernetes packages at current version
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        allow_unauthenticated: yes
        autoremove: no
        force: yes
        install_recommends: no
        force_apt_get: yes
      with_items:
        - kubelet
        - kubeadm
        - kubectl

    - name: Clone the GitHub repository
      git:
        repo: "{{ github_repo }}"
        dest: "{{ app_directory }}"
        force: yes

    - name: Build Docker image from repo
      community.docker.docker_image:
        build:
          path: "{{ app_directory }}"
        name: "{{ docker_image_name }}"
