- name: Deploy Flask app in home directory
  hosts: all
  become: yes

  vars:
    flask_repo: "https://github.com/petersimeth/basic-flask-template.git"
    flask_app_dir: "app"  # oder "~" geht auch
    flask_app_file: "app.py"         # oder main.py – je nachdem

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install system packages
      package:
        name:
          - git
          - python3
          - python3-pip
          - python3-flask
        state: present

    - name: Clone Flask app into home directory
      git:
        repo: "{{ flask_repo }}"
        dest: "{{ flask_app_dir }}"
        version: HEAD
        force: yes
        update: yes

    - name: Start Flask app with nohup
      shell: nohup flask run --host=0.0.0.0 > flask.log 2>&1 &
      args:
        chdir: /home/ubuntu/app
