- name: Get token and server URL from server node
  set_fact:
    k3s_token: "{{ hostvars['k3s_token_host']['k3s_token'] }}"
    k3s_server_url: "{{ hostvars['k3s_token_host']['k3s_server_url'] }}"

- name: Install K3s agent
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL="{{ k3s_server_url }}" K3S_TOKEN="{{ k3s_token }}" sh -
  args:
    creates: /usr/local/bin/k3s-agent
